jamaball/JIF-2355-Mapping-Violence-In-Modern-Italy

- mvproject/mvproject/settings.py
- src/Api.js
- src/Map.jsx
Map points draw from the database
> Map plotting

- src/App.js
- src/Map.jsx
Fixed Timeline slider and added the Weapon Filter to the map as well
> Timeline slider

- src/App.js
- src/Map.jsx
Stuff got overwritten, this adds the extra buttons for filtering by weapon and conviction
> Fixing github stuff idk

- src/App.js
> Weapon names

- src/Map.jsx
Point popup now contains more information about the date, location, weapon, conviction, and description of the event.
> Add more info in point popup

- src/Map.css
Modified button alignments to make the map on the lefthand side and all controls focused on the right and below the map.
> Main Page Layout Overhaul

- src/Map.css
- src/Map.jsx
- src/index.css
Altered the entire button system to be left-aligned on the right side of the screen so that the entire filtering system is much more aesthetic.
> Filtering overhaul

- src/assets/data.txt
The sample point data used to test features of the application is now included in the assets folder.
> Add point data to asset folder

- src/App.css
- src/App.js
- src/LoginPage.jsx
- src/MapPage.jsx
Reformatted all UI navigation buttons between the 2 pages so the UI remains coherent and consistent across the entire site
> Log in UI ver1.1

- src/App.css
- src/LoginPage.jsx
- src/MapPage.jsx
Altered Timeline slider to contain multiple classes. This allows us to alter the look of the slider to match the theme and be reconfigured to fit inside the Data Filtering Section of the map page.
> Timeline UI Update

- src/App.css
- src/LoginPage.jsx
- src/MapPage.jsx
Overhauled the UI and CSS for all styles of input both for the filtering system and the log in page, so now the whole site looks much more polished. However, still need to implements filtering from old button systems into the new checkmark system by entering the submit button
> Updated User input Formatting

- mvproject/crimes/views.py
Updated the serializer so that you can post more than one data point at a time.
> made it so you can upload more than one point

- src/Map.jsx
- src/MapPage.jsx
Added a second label to the slider s.t. it now encompasses the entire range you are currently searching within.
> Altered Time Slider Label

- src/Map.jsx
Changed the size of the data points to make them easier to click and view
> Updating data points

- src/Map.jsx
- src/MapPage.jsx
Adds a new button to recenter the map to the default position and zoom level.
> Add button to center map

- src/Map.jsx
Added ability to remove the markers from the map
> Remove Markers

- src/Map.jsx
- src/MapPage.jsx
This adds another georeferenced map layer with a button to toggle the visibility.
> Add another georeferenced map

- src/Map.jsx
- src/MapPage.jsx
This adds another smaller map layer and a corresponding toggle button.
> Add another georeferenced map layer

- src/Map.jsx
This changes the map layer toggle button to zoom into the small map layer.
> Add zoom to small map layer

- src/App.css
Sectioned off and rearranged code so that relevant  css classes were grouped together. Also added Comments to App.css to explain portions to client
> Documented and Refurbished Code

- src/App.css
- src/MapPage.jsx
Reformatted code to ensure clarity of final product to clients. Also added comments to main webpage code to ensure easy handoff to client such that they can continue work once our team reaches completion.
> Distribution reformatting comments

- src/Map.css
Added relevant comments to aspects of the code and removed depreciated aspects of the code itself to better improve code comprehension during handoff of product to client.
> Improved Comprehension
